MessagePack for C++: msgpack::vrefbuffer Class Reference
msgpack::vrefbuffer Class Reference
#include <vrefbuffer.hpp>
Public Member Functions
vrefbuffer (size_t ref_size=MSGPACK_VREFBUFFER_REF_SIZE, size_t chunk_size=MSGPACK_VREFBUFFER_CHUNK_SIZE)
~vrefbuffer ()
void write (const char *buf, size_t len)
void append_ref (const char *buf, size_t len)
void append_copy (const char *buf, size_t len)
const iovec * vector () const
size_t vector_size () const
void migrate (vrefbuffer *to)
void clear ()
vrefbuffer (const vrefbuffer &)=delete
vrefbuffer & operator= (const vrefbuffer &)=delete
Constructor & Destructor Documentation
vrefbuffer() [1/2]
msgpack::vrefbuffer::vrefbuffer (size_t ref_size = MSGPACK_VREFBUFFER_REF_SIZE, size_t chunk_size = MSGPACK_VREFBUFFER_CHUNK_SIZE) inline
References MSGPACK_NULLPTR.
~vrefbuffer()
msgpack::vrefbuffer::~vrefbuffer () inline
vrefbuffer() [2/2]
msgpack::vrefbuffer::vrefbuffer (const vrefbuffer &) delete
Member Function Documentation
append_copy()
void msgpack::vrefbuffer::append_copy (const char * buf, size_t len) inline
References append_ref().
Referenced by write().
append_ref()
void msgpack::vrefbuffer::append_ref (const char * buf, size_t len) inline
References msgpack::iovec::iov_base, and msgpack::iovec::iov_len.
Referenced by append_copy(), and write().
clear()
void msgpack::vrefbuffer::clear () inline
References MSGPACK_NULLPTR.
migrate()
void msgpack::vrefbuffer::migrate (vrefbuffer * to) inline
References MSGPACK_NULLPTR.
operator=()
vrefbuffer& msgpack::vrefbuffer::operator= (const vrefbuffer &) delete
vector()
const iovec* msgpack::vrefbuffer::vector () const inline
vector_size()
size_t msgpack::vrefbuffer::vector_size () const inline
write()
void msgpack::vrefbuffer::write (const char * buf, size_t len) inline
References append_copy(), and append_ref().
The documentation for this class was generated from the following file:
msgpack/v1/vrefbuffer.hpp