MessagePack for C++: msgpack::detail::context< VisitorHolder > Class Template Reference
msgpack::detail::context< VisitorHolder > Class Template Reference
#include <unpack.hpp>
Public Member Functions
context (unpack_reference_func f, void *user_data, unpack_limit const &limit)
void init ()
msgpack::object const & data () const
unpack_user & user ()
unpack_user const & user () const
int execute (const char *data, std::size_t len, std::size_t &off)
template<>
void check_ext_size (std::size_t size)
Constructor & Destructor Documentation
context()
template<typename VisitorHolder > msgpack::detail::context< VisitorHolder >::context (unpack_reference_func f, void * user_data, unpack_limit const & limit) inline
References MSGPACK_EMBED_STACK_SIZE.
Member Function Documentation
check_ext_size()
template<typename VisitorHolder > template<> void msgpack::detail::context< VisitorHolder >::check_ext_size (std::size_t size) inline
References msgpack::type::size().
data()
template<typename VisitorHolder > msgpack::object const& msgpack::detail::context< VisitorHolder >::data () const inline
Referenced by msgpack::unpacker::data(), msgpack::detail::context< VisitorHolder >::execute(), and msgpack::detail::unpack_imp().
execute()
template<typename VisitorHolder > int msgpack::detail::context< VisitorHolder >::execute (const char * data, std::size_t len, std::size_t & off) inline
References msgpack::detail::context< VisitorHolder >::data(), MSGPACK_ACS_BIN_VALUE, MSGPACK_ACS_EXT_VALUE, MSGPACK_ACS_STR_VALUE, MSGPACK_CS_ARRAY_16, MSGPACK_CS_ARRAY_32, MSGPACK_CS_BIN_16, MSGPACK_CS_BIN_32, MSGPACK_CS_BIN_8, MSGPACK_CS_DOUBLE, MSGPACK_CS_EXT_16, MSGPACK_CS_EXT_32, MSGPACK_CS_EXT_8, MSGPACK_CS_FIXEXT_1, MSGPACK_CS_FIXEXT_16, MSGPACK_CS_FIXEXT_2, MSGPACK_CS_FIXEXT_4, MSGPACK_CS_FIXEXT_8, MSGPACK_CS_FLOAT, MSGPACK_CS_HEADER, MSGPACK_CS_INT_16, MSGPACK_CS_INT_32, MSGPACK_CS_INT_64, MSGPACK_CS_INT_8, MSGPACK_CS_MAP_16, MSGPACK_CS_MAP_32, MSGPACK_CS_STR_16, MSGPACK_CS_STR_32, MSGPACK_CS_STR_8, MSGPACK_CS_UINT_16, MSGPACK_CS_UINT_32, MSGPACK_CS_UINT_64, MSGPACK_CS_UINT_8, MSGPACK_CT_ARRAY_ITEM, MSGPACK_CT_MAP_KEY, MSGPACK_NULLPTR, msgpack::detail::unpack_bin(), msgpack::detail::unpack_double(), msgpack::detail::unpack_ext(), msgpack::detail::unpack_false(), msgpack::detail::unpack_float(), msgpack::detail::unpack_int16(), msgpack::detail::unpack_int32(), msgpack::detail::unpack_int64(), msgpack::detail::unpack_int8(), msgpack::detail::unpack_nil(), msgpack::detail::unpack_str(), msgpack::detail::unpack_true(), msgpack::detail::unpack_uint16(), msgpack::detail::unpack_uint32(), msgpack::detail::unpack_uint64(), and msgpack::detail::unpack_uint8().
Referenced by msgpack::detail::unpack_imp().
init()
template<typename VisitorHolder > void msgpack::detail::context< VisitorHolder >::init () inline
References MSGPACK_CS_HEADER.
Referenced by msgpack::unpacker::reset(), msgpack::detail::unpack_imp(), and msgpack::unpacker::unpacker().
user() [1/2]
template<typename VisitorHolder > unpack_user& msgpack::detail::context< VisitorHolder >::user () inline
Referenced by msgpack::unpacker::next(), msgpack::unpacker::release_zone(), msgpack::detail::unpack_imp(), and msgpack::unpacker::unpacker().
user() [2/2]
template<typename VisitorHolder > unpack_user const& msgpack::detail::context< VisitorHolder >::user () const inline
The documentation for this class was generated from the following file:
msgpack/v1/unpack.hpp