MessagePack for C++: msgpack::fbuffer Class Reference
msgpack::fbuffer Class Reference
#include <fbuffer.hpp>
Public Member Functions
fbuffer (FILE *file)
void write (const char *buf, unsigned int len)
FILE * file () const
fbuffer (const fbuffer &)=delete
fbuffer & operator= (const fbuffer &)=delete
Constructor & Destructor Documentation
msgpack::fbuffer::fbuffer (FILE * file) inline explicit
Referenced by file().
msgpack::fbuffer::fbuffer (const fbuffer &) delete
Member Function Documentation
FILE* msgpack::fbuffer::file () const inline
References fbuffer(), and operator=().
fbuffer& msgpack::fbuffer::operator= (const fbuffer &) delete
Referenced by file().
void msgpack::fbuffer::write (const char * buf, unsigned int len) inline
The documentation for this class was generated from the following file:
/home/kondo/work/msgpack-c/include/msgpack/v1/fbuffer.hpp