MessagePack for C++: msgpack::sbuffer Class Reference
msgpack::sbuffer Class Reference
#include <sbuffer.hpp>
Public Member Functions
sbuffer (size_t initsz=MSGPACK_SBUFFER_INIT_SIZE)
~sbuffer ()
sbuffer (const sbuffer &)=delete
sbuffer & operator= (const sbuffer &)=delete
sbuffer (sbuffer &&other)
sbuffer & operator= (sbuffer &&other)
void write (const char *buf, size_t len)
char * data ()
const char * data () const
size_t size () const
char * release ()
void clear ()
Constructor & Destructor Documentation
msgpack::sbuffer::sbuffer (size_t initsz = MSGPACK_SBUFFER_INIT_SIZE) inline
Referenced by clear(), and ~sbuffer().
msgpack::sbuffer::~sbuffer () inline
References operator=(), and sbuffer().
msgpack::sbuffer::sbuffer (const sbuffer &) delete
msgpack::sbuffer::sbuffer (sbuffer && other) inline
Member Function Documentation
void msgpack::sbuffer::clear () inline
References MSGPACK_SBUFFER_INIT_SIZE, operator=(), and sbuffer().
char* msgpack::sbuffer::data () inline
const char* msgpack::sbuffer::data () const inline
sbuffer& msgpack::sbuffer::operator= (const sbuffer &) delete
Referenced by clear(), and ~sbuffer().
sbuffer& msgpack::sbuffer::operator= (sbuffer && other) inline
char* msgpack::sbuffer::release () inline
size_t msgpack::sbuffer::size () const inline
void msgpack::sbuffer::write (const char * buf, size_t len) inline
The documentation for this class was generated from the following file:
/home/kondo/work/msgpack-c/include/msgpack/v1/sbuffer.hpp