MessagePack for C++: msgpack::object_parser Class Reference
msgpack::object_parser Class Reference
#include <object.hpp>
Public Member Functions
object_parser (msgpack::object const &obj)
template<typename Visitor >
void parse (Visitor &v)
Constructor & Destructor Documentation
object_parser()
msgpack::object_parser::object_parser (msgpack::object const & obj) inline explicit
Member Function Documentation
parse()
template<typename Visitor > void msgpack::object_parser::parse (Visitor & v) inline
References msgpack::object::union_type::array, msgpack::type::ARRAY, msgpack::object::union_type::bin, msgpack::type::BIN, msgpack::object::union_type::boolean, msgpack::type::BOOLEAN, msgpack::object::union_type::ext, msgpack::type::EXT, msgpack::object::union_type::f64, msgpack::type::FLOAT32, msgpack::type::FLOAT64, msgpack::object::union_type::i64, msgpack::object::union_type::map, msgpack::type::MAP, msgpack::type::NEGATIVE_INTEGER, msgpack::type::NIL, msgpack::type::POSITIVE_INTEGER, msgpack::object_array::ptr, msgpack::object_map::ptr, msgpack::object_str::ptr, msgpack::object_bin::ptr, msgpack::object_ext::ptr, msgpack::object_array::size, msgpack::object_map::size, msgpack::object_str::size, msgpack::object_bin::size, msgpack::object_ext::size, msgpack::object::union_type::str, msgpack::type::STR, msgpack::object::type, msgpack::object::union_type::u64, and msgpack::object::via.
Referenced by msgpack::aligned_zone_size(), msgpack::adaptor::object_with_zone< msgpack::object >::operator()(), msgpack::adaptor::pack< msgpack::object >::operator()(), msgpack::operator<<(), and msgpack::operator==().
The documentation for this class was generated from the following file:
msgpack/v1/object.hpp