MessagePack for C++: msgpack::adaptor::pack< T[N]> Struct Template Reference
msgpack::adaptor::pack< T[N]> Struct Template Reference
#include <carray.hpp>
Public Member Functions
template<typename Stream >
msgpack::packer< Stream > & operator() (msgpack::packer< Stream > &o, const T(&v)[N]) const
Member Function Documentation
operator()()
template<typename T , std::size_t N> template<typename Stream > msgpack::packer<Stream>& msgpack::adaptor::pack< T[N]>::operator() (msgpack< T[N]>::packer< Stream > & o, const T(&) v[N]) const inline
References msgpack::checked_get_container_size(), msgpack::packer< Stream >::pack(), msgpack::packer< Stream >::pack_array(), and msgpack::type::size().
The documentation for this struct was generated from the following file:
msgpack/v1/adaptor/carray.hpp