MessagePack for C++: msgpack::adaptor::object_with_zone< const char[N]> Struct Template Reference
msgpack::adaptor::object_with_zone< const char[N]> Struct Template Reference
#include <carray.hpp>
Public Member Functions
void operator() (msgpack::object::with_zone &o, const char(&v)[N]) const
Member Function Documentation
operator()()
template<std::size_t N> void msgpack::adaptor::object_with_zone< const char[N]>::operator() (msgpack::object::with_zone & o, const char(&) v[N]) const inline
References msgpack::zone::allocate_align(), msgpack::checked_get_container_size(), msgpack::object_str::ptr, msgpack::type::size(), msgpack::object_str::size, msgpack::type::STR, msgpack::object::union_type::str, msgpack::object::type, msgpack::object::via, and msgpack::object::with_zone::zone.
The documentation for this struct was generated from the following file:
/home/kondo/work/msgpack-c/include/msgpack/v1/adaptor/carray.hpp