MessagePack for C++: msgpack::adaptor::pack< std::unordered_map< K, V, Hash, Compare, Alloc > > Struct Template Reference
msgpack::adaptor::pack< std::unordered_map< K, V, Hash, Compare, Alloc > > Struct Template Reference
#include <unordered_map.hpp>
Public Member Functions
template<typename Stream >
msgpack::packer< Stream > & operator() (msgpack::packer< Stream > &o, const std::unordered_map< K, V, Hash, Compare, Alloc > &v) const
Member Function Documentation
operator()()
template<typename K , typename V , typename Hash , typename Compare , typename Alloc > template<typename Stream > msgpack::packer<Stream>& msgpack::adaptor::pack< std::unordered_map< K, V, Hash, Compare, Alloc > >::operator() (msgpack< std::unordered_map< K, V, Hash, Compare, Alloc > >::packer< Stream > & o, const std::unordered_map< K, V, Hash, Compare, Alloc > & v) const inline
References msgpack::checked_get_container_size(), msgpack::packer< Stream >::pack(), msgpack::packer< Stream >::pack_map(), and msgpack::type::size().
The documentation for this struct was generated from the following file:
msgpack/v1/adaptor/cpp11/unordered_map.hpp