MessagePack for C++: msgpack::type::define_map< Args > Struct Template Reference
msgpack::type::define_map< Args > Struct Template Reference
#include <cpp11_define_map.hpp>
Public Member Functions
define_map (Args &... args)
template<typename Packer >
void msgpack_pack (Packer &pk) const
void msgpack_unpack (msgpack::object const &o) const
void msgpack_object (msgpack::object *o, msgpack::zone &z) const
Public Attributes
std::tuple< Args &... > a
Constructor & Destructor Documentation
define_map()
template<typename... Args> msgpack::type::define_map< Args >::define_map (Args &... args) inline
Member Function Documentation
msgpack_object()
template<typename... Args> void msgpack::type::define_map< Args >::msgpack_object (msgpack::object * o, msgpack::zone & z) const inline
References msgpack::type::define_map< Args >::a, msgpack::zone::allocate_align(), msgpack::object::union_type::map, msgpack::type::MAP, MSGPACK_ZONE_ALIGNOF, msgpack::object_map::ptr, msgpack::object_map::size, msgpack::object::type, and msgpack::object::via.
msgpack_pack()
template<typename... Args> template<typename Packer > void msgpack::type::define_map< Args >::msgpack_pack (Packer & pk) const inline
References msgpack::type::define_map< Args >::a, and msgpack::pack().
msgpack_unpack()
template<typename... Args> void msgpack::type::define_map< Args >::msgpack_unpack (msgpack::object const & o) const inline
References msgpack::type::define_map< Args >::a, msgpack::object_kv::key, msgpack::object::union_type::map, msgpack::type::MAP, msgpack::object_map::ptr, msgpack::object_str::ptr, msgpack::object_map::size, msgpack::object_str::size, msgpack::object::union_type::str, msgpack::type::STR, msgpack::object::type, msgpack::unpack(), msgpack::object_kv::val, and msgpack::object::via.
Member Data Documentation
a
template<typename... Args> std::tuple<Args&...> msgpack::type::define_map< Args >::a
Referenced by msgpack::type::define_map< Args >::msgpack_object(), msgpack::type::define_map< Args >::msgpack_pack(), and msgpack::type::define_map< Args >::msgpack_unpack().
The documentation for this struct was generated from the following file:
msgpack/v1/adaptor/detail/cpp11_define_map.hpp