MessagePack for C++: msgpack::detail::unpack_array Struct Reference
msgpack::detail::unpack_array Struct Reference
#include <unpack.hpp>
Public Member Functions
void operator() (unpack_user &u, uint32_t n, msgpack::object &o) const
Member Function Documentation
operator()()
void msgpack::detail::unpack_array::operator() (unpack_user & u, uint32_t n, msgpack::object & o) const inline
References msgpack::zone::allocate_align(), msgpack::object::union_type::array, msgpack::type::ARRAY, msgpack::unpack_limit::array(), msgpack::detail::unpack_user::limit(), MSGPACK_ZONE_ALIGNOF, msgpack::object_array::ptr, msgpack::type::size(), msgpack::object_array::size, msgpack::object::type, msgpack::object::via, and msgpack::detail::unpack_user::zone().
The documentation for this struct was generated from the following file:
msgpack/v1/unpack.hpp