MessagePack for C++: msgpack::adaptor::pack< T, typename msgpack::enable_if< detail::is_seq_no_pair_no_tuple< T >::value >::type > Struct Template Reference
msgpack::adaptor::pack< T, typename msgpack::enable_if< detail::is_seq_no_pair_no_tuple< T >::value >::type > Struct Template Reference
#include <fusion.hpp>
Public Member Functions
template<typename Stream >
msgpack::packer< Stream > & operator() (msgpack::packer< Stream > &o, const T &v) const
Member Function Documentation
operator()()
template<typename T > template<typename Stream > msgpack::packer<Stream>& msgpack::adaptor::pack< T, typename msgpack::enable_if< detail::is_seq_no_pair_no_tuple< T >::value >::type >::operator() (msgpack< T, typename msgpack::enable_if< detail::is_seq_no_pair_no_tuple< T >::value >::type >::packer< Stream > & o, const T & v) const inline
References msgpack::checked_get_container_size(), msgpack::packer< Stream >::pack_array(), and msgpack::type::size().
The documentation for this struct was generated from the following file:
msgpack/v1/adaptor/boost/fusion.hpp