MessagePack for C++: msgpack::object_pack_visitor< Stream > Struct Template Reference
msgpack::object_pack_visitor< Stream > Struct Template Reference
#include <object.hpp>
Public Member Functions
object_pack_visitor (msgpack::packer< Stream > &pk)
bool visit_nil ()
bool visit_boolean (bool v)
bool visit_positive_integer (uint64_t v)
bool visit_negative_integer (int64_t v)
bool visit_float32 (float v)
bool visit_float64 (double v)
bool visit_str (const char *v, uint32_t size)
bool visit_bin (const char *v, uint32_t size)
bool visit_ext (const char *v, uint32_t size)
bool start_array (uint32_t num_elements)
bool start_array_item ()
bool end_array_item ()
bool end_array ()
bool start_map (uint32_t num_kv_pairs)
bool start_map_key ()
bool end_map_key ()
bool start_map_value ()
bool end_map_value ()
bool end_map ()
Constructor & Destructor Documentation
object_pack_visitor()
template<typename Stream > msgpack::object_pack_visitor< Stream >::object_pack_visitor (msgpack::packer< Stream > & pk) inline explicit
Member Function Documentation
end_array()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::end_array () inline
end_array_item()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::end_array_item () inline
end_map()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::end_map () inline
end_map_key()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::end_map_key () inline
end_map_value()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::end_map_value () inline
start_array()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::start_array (uint32_t num_elements) inline
start_array_item()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::start_array_item () inline
start_map()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::start_map (uint32_t num_kv_pairs) inline
start_map_key()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::start_map_key () inline
start_map_value()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::start_map_value () inline
visit_bin()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::visit_bin (const char * v, uint32_t size) inline
References msgpack::type::size().
visit_boolean()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::visit_boolean (bool v) inline
visit_ext()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::visit_ext (const char * v, uint32_t size) inline
References msgpack::type::size().
visit_float32()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::visit_float32 (float v) inline
visit_float64()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::visit_float64 (double v) inline
visit_negative_integer()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::visit_negative_integer (int64_t v) inline
visit_nil()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::visit_nil () inline
visit_positive_integer()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::visit_positive_integer (uint64_t v) inline
visit_str()
template<typename Stream > bool msgpack::object_pack_visitor< Stream >::visit_str (const char * v, uint32_t size) inline
References msgpack::type::size().
The documentation for this struct was generated from the following file:
msgpack/v1/object.hpp