MessagePack for C++: msgpack::adaptor::detail::array::as_impl< T, N > Struct Template Reference
msgpack::adaptor::detail::array::as_impl< T, N > Struct Template Reference
#include <array.hpp>
Static Public Member Functions
static std::array< T, N > as (msgpack::object const &o)
Member Function Documentation
as()
template<typename T , std::size_t N> static std::array<T, N> msgpack::adaptor::detail::array::as_impl< T, N >::as (msgpack::object const & o) inline static
References msgpack::object::union_type::array, msgpack::object::as(), msgpack::adaptor::detail::array::concat(), msgpack::object_array::ptr, and msgpack::object::via.
Referenced by msgpack::adaptor::as< std::array< T, N >, typename std::enable_if< msgpack::has_as< T >::value >::type >::operator()().
The documentation for this struct was generated from the following file:
/home/kondo/work/msgpack-c/include/msgpack/v1/adaptor/cpp11/array.hpp