MessagePack for C++: msgpack::adaptor::pack< std::vector< T, Alloc > > Struct Template Reference
msgpack::adaptor::pack< std::vector< T, Alloc > > Struct Template Reference
#include <vector.hpp>
Public Member Functions
template<typename Stream >
msgpack::packer< Stream > & operator() (msgpack::packer< Stream > &o, const std::vector< T, Alloc > &v) const
Member Function Documentation
operator()()
template<typename T , typename Alloc > template<typename Stream > msgpack::packer<Stream>& msgpack::adaptor::pack< std::vector< T, Alloc > >::operator() (msgpack< std::vector< T, Alloc > >::packer< Stream > & o, const std::vector< T, Alloc > & v) const inline
References msgpack::checked_get_container_size(), msgpack::packer< Stream >::pack(), msgpack::packer< Stream >::pack_array(), and msgpack::type::size().
The documentation for this struct was generated from the following file:
/home/kondo/work/msgpack-c/include/msgpack/v1/adaptor/vector.hpp