MessagePack for C++: msgpack::adaptor::pack< msgpack::type::array_ref< T > > Struct Template Reference
msgpack::adaptor::pack< msgpack::type::array_ref< T > > Struct Template Reference
#include <array_ref.hpp>
Public Member Functions
template<typename Stream >
msgpack::packer< Stream > & operator() (msgpack::packer< Stream > &o, const msgpack::type::array_ref< T > &v) const
Member Function Documentation
operator()()
template<typename T > template<typename Stream > msgpack::packer<Stream>& msgpack::adaptor::pack< msgpack::type::array_ref< T > >::operator() (msgpack< msgpack::type::array_ref< T > >::packer< Stream > & o, const msgpack< msgpack::type::array_ref< T > >::type::array_ref< T > & v) const inline
References msgpack::checked_get_container_size(), msgpack::type::array_ref< T >::data, msgpack::packer< Stream >::pack(), msgpack::packer< Stream >::pack_array(), and msgpack::type::array_ref< T >::size().
The documentation for this struct was generated from the following file:
/home/kondo/work/msgpack-c/include/msgpack/v1/adaptor/array_ref.hpp