MessagePack for C++: msgpack::detail::unpack_map Struct Reference
msgpack::detail::unpack_map Struct Reference
#include <unpack.hpp>
Public Member Functions
void operator() (unpack_user &u, uint32_t n, msgpack::object &o) const
Member Function Documentation
operator()()
void msgpack::detail::unpack_map::operator() (unpack_user & u, uint32_t n, msgpack::object & o) const inline
References msgpack::zone::allocate_align(), msgpack::detail::unpack_user::limit(), msgpack::type::MAP, msgpack::object::union_type::map, msgpack::unpack_limit::map(), msgpack::object_map::ptr, msgpack::type::size(), msgpack::object_map::size, msgpack::object::type, msgpack::object::via, and msgpack::detail::unpack_user::zone().
The documentation for this struct was generated from the following file:
/home/kondo/work/msgpack-c/include/msgpack/v1/unpack.hpp