MessagePack for C++: msgpack::object_equal_visitor Struct Reference
msgpack::object_equal_visitor Struct Reference
#include <object.hpp>
Public Member Functions
object_equal_visitor (msgpack::object const &obj, bool &result)
bool visit_nil ()
bool visit_boolean (bool v)
bool visit_positive_integer (uint64_t v)
bool visit_negative_integer (int64_t v)
bool visit_float32 (float v)
bool visit_float64 (double v)
bool visit_str (const char *v, uint32_t size)
bool visit_bin (const char *v, uint32_t size)
bool visit_ext (const char *v, uint32_t size)
bool start_array (uint32_t num_elements)
bool start_array_item ()
bool end_array_item ()
bool end_array ()
bool start_map (uint32_t num_kv_pairs)
bool start_map_key ()
bool end_map_key ()
bool start_map_value ()
bool end_map_value ()
bool end_map ()
Constructor & Destructor Documentation
object_equal_visitor()
msgpack::object_equal_visitor::object_equal_visitor (msgpack::object const & obj, bool & result) inline
Member Function Documentation
end_array()
bool msgpack::object_equal_visitor::end_array () inline
end_array_item()
bool msgpack::object_equal_visitor::end_array_item () inline
end_map()
bool msgpack::object_equal_visitor::end_map () inline
end_map_key()
bool msgpack::object_equal_visitor::end_map_key () inline
end_map_value()
bool msgpack::object_equal_visitor::end_map_value () inline
start_array()
bool msgpack::object_equal_visitor::start_array (uint32_t num_elements) inline
References msgpack::object::union_type::array, msgpack::type::ARRAY, msgpack::object_array::ptr, msgpack::object_array::size, msgpack::object::type, and msgpack::object::via.
start_array_item()
bool msgpack::object_equal_visitor::start_array_item () inline
start_map()
bool msgpack::object_equal_visitor::start_map (uint32_t num_kv_pairs) inline
References msgpack::object::union_type::array, msgpack::object::union_type::map, msgpack::type::MAP, msgpack::object_map::ptr, msgpack::object_array::size, msgpack::object::type, and msgpack::object::via.
start_map_key()
bool msgpack::object_equal_visitor::start_map_key () inline
start_map_value()
bool msgpack::object_equal_visitor::start_map_value () inline
visit_bin()
bool msgpack::object_equal_visitor::visit_bin (const char * v, uint32_t size) inline
References msgpack::object::union_type::bin, msgpack::type::BIN, msgpack::object_bin::ptr, msgpack::type::size(), msgpack::object_bin::size, msgpack::object::type, and msgpack::object::via.
visit_boolean()
bool msgpack::object_equal_visitor::visit_boolean (bool v) inline
References msgpack::object::union_type::boolean, msgpack::type::BOOLEAN, msgpack::object::type, and msgpack::object::via.
visit_ext()
bool msgpack::object_equal_visitor::visit_ext (const char * v, uint32_t size) inline
References msgpack::object::union_type::ext, msgpack::type::EXT, msgpack::object_ext::ptr, msgpack::type::size(), msgpack::object_ext::size, msgpack::object::type, and msgpack::object::via.
visit_float32()
bool msgpack::object_equal_visitor::visit_float32 (float v) inline
References msgpack::object::union_type::f64, msgpack::type::FLOAT32, msgpack::object::type, and msgpack::object::via.
visit_float64()
bool msgpack::object_equal_visitor::visit_float64 (double v) inline
References msgpack::object::union_type::f64, msgpack::type::FLOAT64, msgpack::object::type, and msgpack::object::via.
visit_negative_integer()
bool msgpack::object_equal_visitor::visit_negative_integer (int64_t v) inline
References msgpack::object::union_type::i64, msgpack::type::NEGATIVE_INTEGER, msgpack::object::type, and msgpack::object::via.
visit_nil()
bool msgpack::object_equal_visitor::visit_nil () inline
References msgpack::type::NIL, and msgpack::object::type.
visit_positive_integer()
bool msgpack::object_equal_visitor::visit_positive_integer (uint64_t v) inline
References msgpack::type::POSITIVE_INTEGER, msgpack::object::type, msgpack::object::union_type::u64, and msgpack::object::via.
visit_str()
bool msgpack::object_equal_visitor::visit_str (const char * v, uint32_t size) inline
References msgpack::object_str::ptr, msgpack::type::size(), msgpack::object_str::size, msgpack::object::union_type::str, msgpack::type::STR, msgpack::object::type, and msgpack::object::via.
The documentation for this struct was generated from the following file:
msgpack/v1/object.hpp