MessagePack for C++: msgpack::aligned_zone_size_visitor Struct Reference
msgpack::aligned_zone_size_visitor Struct Reference
#include <object.hpp>
Public Member Functions
aligned_zone_size_visitor (std::size_t &s)
bool visit_nil ()
bool visit_boolean (bool)
bool visit_positive_integer (uint64_t)
bool visit_negative_integer (int64_t)
bool visit_float32 (float)
bool visit_float64 (double)
bool visit_str (const char *, uint32_t size)
bool visit_bin (const char *, uint32_t size)
bool visit_ext (const char *, uint32_t size)
bool start_array (uint32_t num_elements)
bool start_array_item ()
bool end_array_item ()
bool end_array ()
bool start_map (uint32_t num_kv_pairs)
bool start_map_key ()
bool end_map_key ()
bool start_map_value ()
bool end_map_value ()
bool end_map ()
Constructor & Destructor Documentation
aligned_zone_size_visitor()
msgpack::aligned_zone_size_visitor::aligned_zone_size_visitor (std::size_t & s) inline explicit
Member Function Documentation
end_array()
bool msgpack::aligned_zone_size_visitor::end_array () inline
end_array_item()
bool msgpack::aligned_zone_size_visitor::end_array_item () inline
end_map()
bool msgpack::aligned_zone_size_visitor::end_map () inline
end_map_key()
bool msgpack::aligned_zone_size_visitor::end_map_key () inline
end_map_value()
bool msgpack::aligned_zone_size_visitor::end_map_value () inline
start_array()
bool msgpack::aligned_zone_size_visitor::start_array (uint32_t num_elements) inline
References msgpack::aligned_size(), and MSGPACK_ZONE_ALIGNOF.
start_array_item()
bool msgpack::aligned_zone_size_visitor::start_array_item () inline
start_map()
bool msgpack::aligned_zone_size_visitor::start_map (uint32_t num_kv_pairs) inline
References msgpack::aligned_size(), and MSGPACK_ZONE_ALIGNOF.
start_map_key()
bool msgpack::aligned_zone_size_visitor::start_map_key () inline
start_map_value()
bool msgpack::aligned_zone_size_visitor::start_map_value () inline
visit_bin()
bool msgpack::aligned_zone_size_visitor::visit_bin (const char * , uint32_t size) inline
References msgpack::aligned_size(), MSGPACK_ZONE_ALIGNOF, and msgpack::type::size().
visit_boolean()
bool msgpack::aligned_zone_size_visitor::visit_boolean (bool) inline
visit_ext()
bool msgpack::aligned_zone_size_visitor::visit_ext (const char * , uint32_t size) inline
References msgpack::aligned_size(), MSGPACK_ZONE_ALIGNOF, and msgpack::type::size().
visit_float32()
bool msgpack::aligned_zone_size_visitor::visit_float32 (float) inline
visit_float64()
bool msgpack::aligned_zone_size_visitor::visit_float64 (double) inline
visit_negative_integer()
bool msgpack::aligned_zone_size_visitor::visit_negative_integer (int64_t) inline
visit_nil()
bool msgpack::aligned_zone_size_visitor::visit_nil () inline
visit_positive_integer()
bool msgpack::aligned_zone_size_visitor::visit_positive_integer (uint64_t) inline
visit_str()
bool msgpack::aligned_zone_size_visitor::visit_str (const char * , uint32_t size) inline
References msgpack::aligned_size(), MSGPACK_ZONE_ALIGNOF, and msgpack::type::size().
The documentation for this struct was generated from the following file:
msgpack/v1/object.hpp