MessagePack for C++: msgpack::type::define_array<> Struct Template Reference
msgpack::type::define_array<> Struct Template Reference
#include <cpp03_define_array.hpp>
Public Types
typedef define_array value_type
typedef tuple tuple_type
typedef define_array value_type
typedef std::tuple tuple_type
Public Member Functions
template<typename Packer >
void msgpack_pack (Packer &pk) const
void msgpack_unpack (msgpack::object const &o)
void msgpack_object (msgpack::object *o, msgpack::zone &) const
template<typename Packer >
void msgpack_pack (Packer &pk) const
void msgpack_unpack (msgpack::object const &o)
void msgpack_object (msgpack::object *o, msgpack::zone &) const
Member Typedef Documentation
typedef tuple msgpack::type::define_array<>::tuple_type
typedef std::tuple msgpack::type::define_array<>::tuple_type
typedef define_array msgpack::type::define_array<>::value_type
typedef define_array msgpack::type::define_array<>::value_type
Member Function Documentation
void msgpack::type::define_array<>::msgpack_object (msgpack::object * o, msgpack::zone &) const inline
References msgpack::zone::allocate_align(), msgpack::type::ARRAY, msgpack::object::union_type::array, msgpack::object::convert(), msgpack::type::define_array< Args >::define_array(), msgpack::type::define_array< Args >::msgpack_object(), msgpack::type::define_array< Args >::msgpack_pack(), msgpack::type::define_array< Args >::msgpack_unpack(), msgpack::object_array::ptr, msgpack::object_array::size, msgpack::object::type, and msgpack::object::via.
void msgpack::type::define_array<>::msgpack_object (msgpack::object * o, msgpack::zone &) const inline
References msgpack::type::ARRAY, msgpack::object::union_type::array, msgpack::type::make_define_array(), msgpack::object_array::ptr, msgpack::object_array::size, msgpack::object::type, and msgpack::object::via.
template<typename Packer > void msgpack::type::define_array<>::msgpack_pack (Packer & pk) const inline
template<typename Packer > void msgpack::type::define_array<>::msgpack_pack (Packer & pk) const inline
void msgpack::type::define_array<>::msgpack_unpack (msgpack::object const & o) inline
References msgpack::type::ARRAY, and msgpack::object::type.
void msgpack::type::define_array<>::msgpack_unpack (msgpack::object const & o) inline
References msgpack::type::ARRAY, and msgpack::object::type.
The documentation for this struct was generated from the following files:
/home/kondo/work/msgpack-c/include/msgpack/v1/adaptor/detail/cpp03_define_array.hpp
/home/kondo/work/msgpack-c/include/msgpack/v1/adaptor/detail/cpp11_define_array.hpp