MessagePack for C++: msgpack::type::define_array_imp< Tuple, N > Struct Template Reference
msgpack::type::define_array_imp< Tuple, N > Struct Template Reference
#include <cpp11_define_array.hpp>
Static Public Member Functions
template<typename Packer >
static void pack (Packer &pk, Tuple const &t)
static void unpack (msgpack::object const &o, Tuple &t)
static void object (msgpack::object *o, msgpack::zone &z, Tuple const &t)
Member Function Documentation
template<typename Tuple , std::size_t N> static void msgpack::type::define_array_imp< Tuple, N >::object (msgpack::object * o, msgpack::zone & z, Tuple const & t) inline static
References msgpack::object::union_type::array, msgpack::object_array::ptr, and msgpack::object::via.
template<typename Tuple , std::size_t N> template<typename Packer > static void msgpack::type::define_array_imp< Tuple, N >::pack (Packer & pk, Tuple const & t) inline static
Referenced by msgpack::type::define_array< Args >::msgpack_pack().
template<typename Tuple , std::size_t N> static void msgpack::type::define_array_imp< Tuple, N >::unpack (msgpack::object const & o, Tuple & t) inline static
References msgpack::object::union_type::array, msgpack::object::convert(), msgpack::object_array::ptr, msgpack::object_array::size, and msgpack::object::via.
Referenced by msgpack::type::define_array< Args >::msgpack_unpack().
The documentation for this struct was generated from the following file:
/home/kondo/work/msgpack-c/include/msgpack/v1/adaptor/detail/cpp11_define_array.hpp