MessagePack for C++: msgpack::adaptor::object_with_zone< type::assoc_vector< K, V, Compare, Alloc > > Struct Template Reference
msgpack::adaptor::object_with_zone< type::assoc_vector< K, V, Compare, Alloc > > Struct Template Reference
#include <map.hpp>
Public Member Functions
void operator() (msgpack::object::with_zone &o, const type::assoc_vector< K, V, Compare, Alloc > &v) const
Member Function Documentation
operator()()
template<typename K , typename V , typename Compare , typename Alloc > void msgpack::adaptor::object_with_zone< type::assoc_vector< K, V, Compare, Alloc > >::operator() (msgpack::object::with_zone & o, const type::assoc_vector< K, V, Compare, Alloc > & v) const inline
References msgpack::zone::allocate_align(), msgpack::checked_get_container_size(), msgpack::object_kv::key, msgpack::object::union_type::map, msgpack::type::MAP, MSGPACK_NULLPTR, MSGPACK_ZONE_ALIGNOF, msgpack::object_map::ptr, msgpack::type::size(), msgpack::object_map::size, msgpack::object::type, msgpack::object_kv::val, msgpack::object::via, and v2::object::with_zone::zone.
The documentation for this struct was generated from the following file:
msgpack/v1/adaptor/map.hpp